### ISSUE TITLE
Team Plan

### ISSUE THREAD

**Issue by WillGoldstein** [WebleIT/LaravelSparkDynamicPlanProvider#1]
Hi,

First, thanks for making this!

I had a couple questions. Can you use this for Spark::teamPlan ? I noticed in your [documentation](https://github.com/WebleIT/LaravelSparkDynamicPlanProvider/blob/master/src/DynamicPlanServiceProvider.php) that it seems to be only registering Spark::Plan in registerSparkPlans($plans). 

Another question is, can I use this to make plans on the fly from the client side (Like let the client say how much of x feature he wants, price it using a server side calculator, then if he/she selects that plan, create and assign the client to it)? 

Thanks!

**Comment by Skullbock** [comment]
Hi @Farbed 
Sorry for not replying sooner. Github has a way of not sending me the notifications for my issues here... have to fix this.

To answer you

1) In theory yes, i've not tested it yet, since my projects where user based and not team based. Let me know if i can help in an way

2) Now that laravel nova is out, the next project i'll deploy with this library , i'll probably create a Nova tool for it

Cheers

**Comment by WillGoldstein** [comment]
Thanks!
